[project]
name = "agent-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "openai>=1.90.0",
    "openai-agents>=0.0.19",
]
